name: SyncCommands
version: ${project.version}
main: io.github.efekurbann.synccommands.SyncCommandsSpigot
api-version: 1.13
authors: [ hyperion ]
description: Spigot-Side of SyncCommands.
commands:
  sync:
    aliases:
      - ssync